%% FUNCTION: calculateConditionalWakeProb
%% INPUTS
% episodes - Numeric matrix of sleep episode properties generated by the 
%            function detectSleepEpisodes

%% OUTPUTS
% max_ep - Numeric matrix (epoch x fly) of the duration of the longest sleep episode 

function max_ep = calculateMaxEpisodeDuration(episodes)

max_ep = zeros(max(episodes(:,2)), max(episodes(:,1)));

for i = 1:size(max_ep,1)
    for j = 1:size(max_ep,2)
        this_epoch_episodes = episodes( find(episodes(:,2) == i & episodes(:,1) == j), 4);
        
        if( ~isempty(this_epoch_episodes))
            max_ep(i,j) = max(this_epoch_episodes);
        else
            max_ep(i,j) = 0;
        end
    end
end

end