%% FUNCTION: calculateNumberSleepEpisodes
%% INPUTS
% episodes - Numeric matrix of sleep episode properties generated by the 
%            function detectSleepEpisodes

%% OUTPUTS
% total - Numeric matrix (epoch x fly) of the number of sleep episodes in
%         the epoch

function total = calculateNumberSleepEpisodes(episodes)

total = zeros(max(episodes(:,2)), max(episodes(:,1)));

for i = 1:size(total,1)
    for j = 1:size(total,2)
        total(i,j) = length(find(episodes(:,2) == i & episodes(:,1) == j));
    end
end

end
