%% FUNCTION: calculateSleepLatency
%% INPUTS
% episodes - Numeric matrix of sleep episode properties generated by the 
%            function detectSleepEpisodes

%% OUTPUTS
% latency - Numeric matrix (epoch x fly) of the time from the beginning of
%           the epoch to the start of the first sleep episode

function latency = calculateSleepLatency(episodes)

latency = zeros(max(episodes(:,2)), max(episodes(:,1)));

for i = 1:size(latency,1)
    for j = 1:size(latency,2)
        if( ~isempty(episodes( find(episodes(:,2) == i & episodes(:,1) == j), 4)))
            latency(i,j) = min(episodes( find(episodes(:,2) == i & episodes(:,1) == j), 3)) - 1;
        else
            latency(i,j) = -1;
        end
    end
end

end