%% FUNCTION: calculateConditionalWakeProb
%% INPUTS
% episodes - Numeric matrix of sleep episode properties generated by the 
%            function detectSleepEpisodes

%% OUTPUTS
% mean_ep - Numeric matrix (epoch x fly) of the duration of the mean sleep episode 

function mean_ep = calculateMeanEpisodeDuration(episodes)

mean_ep = zeros(max(episodes(:,2)), max(episodes(:,1)));

for i = 1:size(mean_ep,1)
    for j = 1:size(mean_ep,2)
        this_epoch_episodes = episodes( find(episodes(:,2) == i & episodes(:,1) == j), 4);
        
        if( ~isempty(this_epoch_episodes))
            total        = sum(this_epoch_episodes);
            number       = length(this_epoch_episodes);
            mean_ep(i,j) = total / number;
        else
            mean_ep(i,j) = 0;
        end
    end
end

end